# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Sphinx Build
        uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: "docs/"
          build-command: "sphinx-build -b html . _build"
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/_build/html/
      # Publish built docs to main branch.
      # ===============================
      - name: Commit documentation changes
        run: |
          git clone https://github.com/GruppoProgettoSWENG21/PaperAssignmentSystem.git --branch main --single-branch main
          cp -r docs/_build/html/* main/
          cd main
          touch .nojekyll
          #git config --local user.email "action@github.com"
          #git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # that.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          directory: main
