# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install pytest
        pip install pytest-cov
        pip install -r requirements.txt
    - name: Test with pytest and coverage
      run: |
        python -m pytest --cov-report xml --cov=./ 
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        directory: ./
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unittests
